# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9ac2afa66b7e3f0a038c56dc8a38f72008cbee4816408f6a1ab32b104ea76f40272f695198bed44b4df7ce6329d4e989f4cf23f10c90642a78bcabbd30d10246

test:
  secret_key_base: 5ab5d496af3473948fc2b6a7c20f63075a1dc68ae0a1969ce9631d928d6d4827578d6011fa02453759ade6df21e2bf39116945b448b3208aea01a3d78964b114

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
